<?php
/**
 * Full import form template.
 *
 * @package MksDdn\MigrateContent
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
?>
<h3><?php esc_html_e( 'Import', 'mksddn-migrate-content' ); ?></h3>
<form method="post" enctype="multipart/form-data" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>" id="mksddn-mc-full-import-form" data-mksddn-full-import="true">
	<?php wp_nonce_field( 'mksddn_mc_full_import' ); ?>
	<input type="hidden" name="action" value="mksddn_mc_import_full">
	
	<div class="mksddn-mc-import-source-toggle">
		<label>
			<input type="radio" name="import_source" value="upload" checked>
			<?php esc_html_e( 'Upload file', 'mksddn-migrate-content' ); ?>
		</label>
		<label>
			<input type="radio" name="import_source" value="server">
			<?php esc_html_e( 'Select from server', 'mksddn-migrate-content' ); ?>
		</label>
	</div>

	<div class="mksddn-mc-import-source-upload">
		<p><?php esc_html_e( 'Upload a .wpbkp archive generated by this plugin. Large files will switch to chunked upload automatically.', 'mksddn-migrate-content' ); ?></p>
		<input type="file" name="full_import_file" accept=".wpbkp" id="mksddn-mc-full-import-file">
	</div>

	<div class="mksddn-mc-import-source-server" style="display: none;">
		<p><?php esc_html_e( 'Select a .wpbkp archive from the server imports directory.', 'mksddn-migrate-content' ); ?></p>
		<select name="server_file" id="mksddn-mc-full-server-file" style="width: 100%; max-width: 500px;">
			<option value=""><?php esc_html_e( 'Select a file...', 'mksddn-migrate-content' ); ?></option>
		</select>
	</div>

	<br>
	<button type="submit" class="button button-secondary"><?php esc_html_e( 'Import Full Site', 'mksddn-migrate-content' ); ?></button>
</form>

<script>
(function() {
	const form = document.getElementById('mksddn-mc-full-import-form');
	if (!form) return;

	const uploadRadio = form.querySelector('input[value="upload"]');
	const serverRadio = form.querySelector('input[value="server"]');
	const uploadDiv = form.querySelector('.mksddn-mc-import-source-upload');
	const serverDiv = form.querySelector('.mksddn-mc-import-source-server');
	const fileInput = form.querySelector('#mksddn-mc-full-import-file');
	const serverSelect = form.querySelector('#mksddn-mc-full-server-file');

	function loadServerFiles() {
		serverSelect.innerHTML = '<option value=""><?php echo esc_js( __( 'Loading...', 'mksddn-migrate-content' ) ); ?></option>';
		
		fetch(ajaxurl, {
			method: 'POST',
			headers: {
				'Content-Type': 'application/x-www-form-urlencoded',
			},
			body: new URLSearchParams({
				action: 'mksddn_mc_get_server_backups',
				nonce: '<?php echo esc_js( wp_create_nonce( 'mksddn_mc_admin' ) ); ?>'
			})
		})
		.then(response => response.json())
		.then(data => {
			if (data.success && data.data.files && data.data.files.length > 0) {
				serverSelect.innerHTML = '<option value=""><?php echo esc_js( __( 'Select a file...', 'mksddn-migrate-content' ) ); ?></option>';
				data.data.files.forEach(file => {
					const option = document.createElement('option');
					option.value = file.name;
					option.textContent = file.name + ' (' + file.size_human + ', ' + file.modified_human + ')';
					serverSelect.appendChild(option);
				});
			} else {
				serverSelect.innerHTML = '<option value=""><?php echo esc_js( __( 'No backup files found', 'mksddn-migrate-content' ) ); ?></option>';
			}
		})
		.catch(error => {
			serverSelect.innerHTML = '<option value=""><?php echo esc_js( __( 'Error loading files', 'mksddn-migrate-content' ) ); ?></option>';
			console.error('Error loading server files:', error);
		});
	}

	function toggleSource() {
		if (uploadRadio.checked) {
			uploadDiv.style.display = 'block';
			serverDiv.style.display = 'none';
			fileInput.required = true;
			serverSelect.required = false;
			serverSelect.value = '';
		} else {
			uploadDiv.style.display = 'none';
			serverDiv.style.display = 'block';
			fileInput.required = false;
			fileInput.value = '';
			serverSelect.required = true;
			loadServerFiles();
		}
	}

	uploadRadio.addEventListener('change', toggleSource);
	serverRadio.addEventListener('change', toggleSource);

	form.addEventListener('submit', function(e) {
		if (serverRadio.checked) {
			if (!serverSelect.value) {
				e.preventDefault();
				alert('<?php echo esc_js( __( 'Please select a file from the server.', 'mksddn-migrate-content' ) ); ?>');
				return false;
			}
			fileInput.removeAttribute('required');
			fileInput.disabled = true;
		} else {
			serverSelect.removeAttribute('required');
		}
	});
})();
</script>

