<?php
/**
 * Full import form template.
 *
 * @package MksDdn\MigrateContent
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
?>
<h3><?php esc_html_e( 'Import', 'mksddn-migrate-content' ); ?></h3>
<form method="post" enctype="multipart/form-data" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>" id="mksddn-mc-full-import-form" data-mksddn-full-import="true">
	<?php wp_nonce_field( 'mksddn_mc_full_import' ); ?>
	<input type="hidden" name="action" value="mksddn_mc_import_full">
	
	<div class="mksddn-mc-import-source-toggle">
		<label>
			<input type="radio" name="import_source" value="upload" checked>
			<?php esc_html_e( 'Upload file', 'mksddn-migrate-content' ); ?>
		</label>
		<label>
			<input type="radio" name="import_source" value="server">
			<?php esc_html_e( 'Select from server', 'mksddn-migrate-content' ); ?>
		</label>
	</div>

	<div class="mksddn-mc-import-source-upload">
		<p><?php esc_html_e( 'Upload a .wpbkp archive generated by this plugin. Large files will switch to chunked upload automatically.', 'mksddn-migrate-content' ); ?></p>
		<input type="file" name="full_import_file" accept=".wpbkp" id="mksddn-mc-full-import-file">
	</div>

	<div class="mksddn-mc-import-source-server" style="display: none;">
		<p><?php esc_html_e( 'Select a .wpbkp archive from the server imports directory.', 'mksddn-migrate-content' ); ?></p>
		<select name="server_file" id="mksddn-mc-full-server-file" style="width: 100%; max-width: 500px;">
			<option value=""><?php esc_html_e( 'Select a file...', 'mksddn-migrate-content' ); ?></option>
		</select>
		<div class="mksddn-mc-server-file-notice notice notice-error" style="display: none; margin-top: 0.5rem;"></div>
	</div>

	<br>
	<button type="submit" class="button button-secondary"><?php esc_html_e( 'Import Full Site', 'mksddn-migrate-content' ); ?></button>
</form>

<script>
(function() {
	function initServerFileSelector() {
		if (typeof window.MksDdnServerFileSelector === 'undefined') {
			// Retry after a short delay if script not loaded yet.
			setTimeout(initServerFileSelector, 100);
			return;
		}

		const form = document.getElementById('mksddn-mc-full-import-form');
		if (!form) return;

		// Check if already initialized.
		if (form.dataset.serverFileSelectorInitialized === 'true') {
			return;
		}

		const selector = new window.MksDdnServerFileSelector({
			form: form,
			uploadRadio: form.querySelector('input[value="upload"]'),
			serverRadio: form.querySelector('input[value="server"]'),
			uploadDiv: form.querySelector('.mksddn-mc-import-source-upload'),
			serverDiv: form.querySelector('.mksddn-mc-import-source-server'),
			fileInput: form.querySelector('#mksddn-mc-full-import-file'),
			serverSelect: form.querySelector('#mksddn-mc-full-server-file'),
			ajaxAction: window.mksddnServerFileSelector ? window.mksddnServerFileSelector.ajaxAction : 'mksddn_mc_get_server_backups',
			nonce: window.mksddnServerFileSelector ? window.mksddnServerFileSelector.nonce : '',
			i18n: window.mksddnServerFileSelector ? window.mksddnServerFileSelector.i18n : {}
		});

		form.dataset.serverFileSelectorInitialized = 'true';
	}

	if (document.readyState === 'loading') {
		document.addEventListener('DOMContentLoaded', initServerFileSelector);
	} else {
		initServerFileSelector();
	}
})();
</script>

