<?php
/**
 * Full import form template.
 *
 * @package MksDdn\MigrateContent
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
?>
<h3><?php esc_html_e( 'Import', 'mksddn-migrate-content' ); ?></h3>
<form method="post" enctype="multipart/form-data" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>" id="mksddn-mc-full-import-form" data-mksddn-full-import="true">
	<?php wp_nonce_field( 'mksddn_mc_full_import' ); ?>
	<input type="hidden" name="action" value="mksddn_mc_import_full">
	<p><?php esc_html_e( 'Upload a .wpbkp archive generated by this plugin. Large files will switch to chunked upload automatically.', 'mksddn-migrate-content' ); ?></p>
	<input type="file" name="full_import_file" accept=".wpbkp" required><br><br>
	<button type="submit" class="button button-secondary"><?php esc_html_e( 'Import Full Site', 'mksddn-migrate-content' ); ?></button>
</form>

